### ISSUE TITLE
single and double quotes always start/stop making text red

### ISSUE THREAD

**Issue by jpluimers** [fruggiero/language-bbcode#1]
See image. There is a quote issue: both single/double quotes seem to open and close sections of 'red' text. I don't think that's the objective of BBcode.

![single quote makes following text red](https://www.dropbox.com/s/mad6u3gis79bfee/Screenshot%202016-05-27%2013.46.28.png?raw=1)

![double quote makes following text red](https://www.dropbox.com/s/nodg4sowbc0dlq3/Screenshot%202016-05-27%2014.00.14.png?raw=1)

You can download the images at https://www.dropbox.com/s/mad6u3gis79bfee/Screenshot%202016-05-27%2013.46.28.png?dl=0 and https://www.dropbox.com/s/nodg4sowbc0dlq3/Screenshot%202016-05-27%2014.00.14.png?dl=0

**Comment by fruggiero** [comment]
Fixed on 0.1.1 version, thanks for submitting the issue! @jpluimers
